my_str = "!!! Harry Potter !!!"
print(my_str.upper())
print(my_str.rstrip("!"))
print(my_str.replace("Harry" , "Usha"))
print(my_str.split(" "))
print(my_str.isalpha())
print(my_str.startswith("!"))
print(my_str.endswith("!"))
print(my_str.find("Potter"))
print(my_str.index("Potter"))
print(my_str.count("!"))
print(my_str.capitalize())
print(my_str.title())
print(my_str.swapcase())
print(my_str.center(50, "*"))